server:
  port: 8085

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  application:
    name: user-platform-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  cloud:
    nacos:
      server-addr: 39.108.67.16
      username: nacos
      password: nacos
      discovery:
        service: user-platform-service

  # redis 配置
  redis:
    # 地址
    host: 39.108.67.16
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: nfsn-redis-6379
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  # 数据库相关
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.67.16:3306/nfsn_business_central_platform?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: nfsn520
    type: com.alibaba.druid.pool.DruidDataSource

swagger:
  title: 接口配置中心
  version: 1.0
  description: 接口配置中心

minio:
  endpoint: http://39.108.67.16:9000
  access-key: IRv1VPs1GveL2R6b
  secret-key: ImS1KMsGg6hLaWCCuwun4E64RvoGmnZP
  bucketName: a-bucket
