server:
  port: 80
spring:
  application:
    name: platform-gateway

  cloud:
    nacos:
      server-addr: 192.168.0.104
      username: nacos
      password: nacos
      discovery:
        namespace: b495cfe0-da32-4ea0-8e89-762871decd43
        group: GROUP_01
        service: user-platform-service