server:
  port: 8090

spring:
  application:
    name: article-platform-service

  cloud:
    nacos:
      server-addr: 192.168.0.104
      username: nacos
      password: nacos
      discovery:
        namespace: b495cfe0-da32-4ea0-8e89-762871decd43
        group: GROUP_01
        service: article-platform-service

  # redis 配置
  redis:
    # 地址
    host: 192.168.0.104
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  # 数据库相关
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.104:3306/vote_active?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 242658
    type: com.alibaba.druid.pool.DruidDataSource