server:
  port: 8095

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  application:
    name: file-service

  cloud:
    nacos:
      server-addr: 39.108.67.16
      username: nacos
      password: nacos
      discovery:
        service: file-service

minio:
  endpoint: http://39.108.67.16:9000
  access-key: IRv1VPs1GveL2R6b
  secret-key: ImS1KMsGg6hLaWCCuwun4E64RvoGmnZP
  bucketName: a-bucket
